server {
    listen 80;
    listen [::]:80;
    # replace localhost to your-domain.com (such as yourdomain.com www.yourdomain.com)
    server_name localhost;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# اولا: تقوم بتشغيل دوكر للسماح لخدمة كيرتبوت بانشاء الشهادات ثم ارجع اضيف هذا السيرفر الحماية. ثانيا: انفذ الامر التالي ادناه
# docker-compose restart nginx
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    replace localhost to your-domain.com (such as yourdomain.com www.yourdomain.com)
    server_name localhost;

    replace localhost to your-domain.com
    ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;

    # اعدادات اضافية لزيادة الامان
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # تحسين أداء الملفات الثابتة لـ Next.js (Caching)
    # هذا المسار يحتوي على ملفات CSS و JS التي لا تتغير كثيراً
    location /_next/static/ {
        proxy_pass http://app:3000; 
        proxy_cache_bypass $http_upgrade; # تجاوز التخزين المؤقت لضمان عمل الاتصالات المباشرة واللحظية مثل WebSockets
        expires 365d; # إخبار المتصفح بحفظ الملف لديه لمدة سنة لتسريع الموقع
        access_log off; # عدم تسجيل هذه الطلبات لتوفير مساحة القرص
    }

    # Reverse Proxy
    location / {
        proxy_pass http://app:3000;

        # تمرير الترويسات (Headers)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # تمرير عنوان IP الحقيقي للزائر (ضروري للتحليلات ومعرفة المستخدمين)
        proxy_set_header X-Real-IP $remote_addr; # عنوان IP الزائر الحقيقي
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # قائمة العناوين التي مر بها الطلب
        proxy_set_header X-Forwarded-Proto $scheme; # إخبار التطبيق أن الزائر يستخدم HTTPS
    }
}